/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package buildout1_shubhampaliwal;
import org.testng.TestNG;
import org.testng.annotations.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

public class AppTest {
	static WebDriver driver;

    // @Test 
	// public void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
	
    // }
@BeforeSuite
public static void createDriver(){
		System.out.println("Initializing driver");
		System.setProperty("webdriver.chrome.driver","D:\\driverChrome\\chromedriver-win64\\chromedriver.exe");  
		ChromeOptions co= new ChromeOptions();
		co.addArguments("--start-maximized"); 
		co.addArguments("--ignore-certificate-errors"); 
		co.addArguments("--disable-popup-blocking");
		co.addArguments("--remote-allow-origins=*");
		co.setBinary("D:\\driverChrome\\chrome-win64\\chrome.exe");
		driver=new ChromeDriver(co); 
		driver.manage().window().maximize();
		System.out.println("browser launched successfully");
}

@Test
public void googleFormAutomation() throws InterruptedException{
GoogleForm form= new GoogleForm(driver);
form.loadUrl();
form.name();
form.yPractiseAutomation();
form.experience();
form.skills();
form.salutationTitle();
form.date7daysAgo();
form.currentTimeNow();
form.submit();
Thread.sleep(5000);
WebElement response= driver.findElement(By.xpath("//div[@class= 'vHW8K']"));
System.out.println(response.getText());
}

@AfterSuite
public void stopTest(){
	driver.close();
	driver.quit();
	System.out.println("Test Completed, driver closed");
}
}
